server:
  port: 8080
spring:
  application:
    name: list
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/word?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON?????????
#mybatis-plus:
#  type-aliases-package: com.hmdp.entity # ?????
logging:
  level:
    cn.lumos: debug

chatgpt:
  api:
    url: https://open.aiproxy.xyz/v1/completions
    apiKey: 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